# Critical system environment variables that should not be deleted
PROTECTED_VARIABLES = {
    'PATH', 'PATHEXT', 'SYSTEMROOT', 'WINDIR', 'COMSPEC', 'TEMP', 'TMP',
    'USERPROFILE', 'HOMEDRIVE', 'HOMEPATH', 'APPDATA', 'LOCALAPPDATA',
    'PROGRAMFILES', 'PROGRAMFILES(X86)', 'PROGRAMDATA', 'SYSTEMDRIVE',
    'PROCESSOR_ARCHITECTURE', 'PROCESSOR_IDENTIFIER', 'NUMBER_OF_PROCESSORS',
    'OS', 'USERNAME', 'USERDOMAIN', 'COMPUTERNAME', 'LOGONSERVER',
    'SESSIONNAME', 'CLIENTNAME', 'USERDNSDOMAIN', 'USERDOMAIN_ROAMINGPROFILE',
    'HOME', 'USER', 'SHELL', 'DISPLAY', 'XDG_SESSION_TYPE', 'DESKTOP_SESSION',
    'LANG', 'LC_ALL', 'LC_CTYPE', 'PWD', 'OLDPWD', 'TERM', 'TMPDIR',
    'LD_LIBRARY_PATH', 'PYTHONPATH', 'JAVA_HOME', 'NODE_PATH'
}

# Variables that require extra confirmation
SENSITIVE_VARIABLES = {
    'PATH', 'PYTHONPATH', 'JAVA_HOME', 'NODE_PATH', 'LD_LIBRARY_PATH',
    'CLASSPATH', 'MAVEN_HOME', 'GRADLE_HOME', 'ANDROID_HOME'
}
